### ISSUE TITLE
answer_container_gen name used in docs instead of answer_container_generator 

### ISSUE THREAD

**Issue by twinters** [magpie-ea/magpie-site#38]
Hi there!

Just wanted to mention some bugs in the example on the `multi_dropdown_customized` example of the [custom views page](https://magpie-ea.github.io/magpie-docs/01_designing_experiments/03_custom_views/):
- It incorrectly names one of the arguments `answer_container_gen`, instead of `answer_container_generator`
- there's a single quotemark missing after the `style='display:none` in the first radiobutton (`o1`), making it a normal radiobutton
- it doesn't seem to create a dropdown menu, but just three buttons instead.

**Comment by x-ji** [comment]
Thanks for the report. Sorry I didn't reply since I am more familiar with the backend part. @marcelklehr would you have something to add regarding this? Or would you say we're currently focused on getting the new Vue-based frontend ready (I guess the old version would still need to be maintained in the meantime?)

**Comment by marcelklehr** [comment]
Sorry, I'm not subscribed to this repo. I agree that we should provide bugfixes for this version of magpie until the newone is ready. The issues should be [fixed](https://github.com/magpie-ea/magpie-docs/commit/f07770c3ab2bf2d8f690d34b233dd0cd6ec959f3) now.
